apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-striking-pelican
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "922541795636"
    kanikoFlags: --skip-unused-stages --snapshotMode=redo
    project: compute-project-183119
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: jenkins-serverless
    repository: gke-cluster-secret
  - key: staging
  - key: production
  ingress:
    domain: 34.66.164.168.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    username: serverless-bot-726
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-tf-jx-striking-pelican-d5ccd2db0227
  - name: reports
    url: gs://reports-tf-jx-striking-pelican-d5ccd2db0227
  - name: repository
    url: gs://repository-tf-jx-striking-pelican-d5ccd2db0227
  vault: {}
  webhook: lighthouse
